<table style="width: 100%; border-collapse: collapse; border: none; background: #f8fafc; border-left: 6px solid #1e3a8a; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
  <tr style="border: none;">
    <td style="vertical-align: middle; border: none; padding: 15px 20px;">
      <h1 style="margin: 0; color: #0f172a; font-size: 2.1em; font-family: system-ui, -apple-system, sans-serif; font-weight: 700; line-height: 1.2;">
        Arrays en Numpy
      </h1>
      <p style="margin: 6px 0 0 0; color: #64748b; font-size: 0.95em; font-family: system-ui, -apple-system, sans-serif;">
        Programación para Ciencia de Datos
      </p>
    </td>
    <td style="vertical-align: middle; text-align: right; border: none; padding: 15px 20px; min-width: 240px; font-family: system-ui, -apple-system, sans-serif;">
      <div style="font-size: 0.9em; color: #334155; line-height: 1.5;">
        <strong style="color: #1e3a8a; font-size: 1em;">Especialización en Ciencia de Datos</strong><br>
        <span style="color: #475569; font-weight: 600;">USTA Tunja</span><br><br>
        <b>Santiago A. Zúñiga M.</b><br>
        ✉️ <a href="mailto:gestorvirtualcienciadatos@ustatunja.edu.co" style="color: #2563eb; text-decoration: none; font-weight: 500;">gestorvirtualcienciadatos@ustatunja.edu.co</a>
      </div>
    </td>
  </tr>
</table>

---
## Arrays en Numpy 

Un **array** es la estructura de datos central de la biblioteca NumPy. En términos simples, es una cuadrícula de valores numéricos que contiene información no solo sobre los datos en sí, sino también sobre cómo interpretarlos matemáticamente. 

A diferencia de las listas tradicionales de Python, un array de NumPy (oficialmente llamado `ndarray`) está diseñado para el **cálculo científico rápido**.



---
### 1. Creación de Arrays 🌱

---
#### 1.1 Desde listas de Python

La forma más básica de crear un array es tomar una lista estándar de Python e inyectarla en NumPy a través de la función `np.array()`.

**¿Por qué convertir una lista a un array?**
* **Las listas de Python** son flexibles: pueden contener enteros, strings y booleanos al mismo tiempo, pero esta flexibilidad las hace muy lentas para calcular matemáticas masivas.
* **Los arrays de NumPy** son rígidos: **todos** los elementos en un array deben ser estrictamente del mismo tipo numérico. Al quitar esa flexibilidad, NumPy puede agrupar la memoria y realizar operaciones matemáticas miles de veces más rápido en código C precompilado.


In [1]:
# Es buena práctica configurar la salida múltiple en Jupyter
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import numpy as np

# Desde una lista de 1 dimensión (Vector 1D)
lista_simple = [1, 2, 3]
array_1d = np.array(lista_simple)
print("Array 1D:", array_1d)

# Desde una lista de listas (Matriz 2D)
lista_anidada = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(lista_anidada)
print("\nMatriz 2D:\n", array_2d)


Array 1D: [1 2 3]

Matriz 2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


---
##### 🛠️ Práctica 1.1: Arrays desde listas



Crea una lista anidada en Python que represente una cuadrícula de 2 filas y 2 columnas con los números del 1 al 4. Luego conviértela a un array de NumPy e imprímela.

In [2]:
# Escribe tu código aquí

# lista_2x2 = ...
# array_practica_1 = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
lista_2x2 = [[1, 2], [3, 4]]
array_practica_1 = np.array(lista_2x2)
print(array_practica_1)
```
</details>


---
#### 1.2 Funciones integradas (Zeros, Ones, Empty)

A menudo en ciencia de datos, necesitas inicializar una matriz de cierto tamaño antes de saber exactamente qué valores irán adentro (por ejemplo, para guardar los resultados de un bucle). Escribir listas anidadas a mano sería imposible para matrices enormes.

Para ello usamos tres funciones clave:

1. **`np.zeros(shape)`**: Crea un array lleno de ceros (`0`). 
   * **¿Para qué sirve?** Funciona como un "lienzo en blanco" (placeholder). Inicializar con ceros garantiza que no haya valores residuales de memoria y es la opción más segura.
2. **`np.ones(shape)`**: Crea un array lleno de unos (`1`).
   * **¿Para qué sirve?** Es útil cuando la inicialización requiere un valor neutral para multiplicaciones matriciales o para aplicar operaciones algebraicas base.
3. **`np.empty(shape)`**: Crea un array asignando el espacio en memoria **sin limpiarlo**. 
   * **¿Para qué sirve?** Es la forma absolutamente más **rápida** de crear un array grande porque no gasta tiempo de CPU escribiendo ceros en la RAM. Sin embargo, el array se creará con "basura" (los últimos números que tu computadora tuvo en ese sector de RAM). ¡Solo úsalo si estás 100% seguro de que vas a sobrescribir **cada uno** de sus elementos inmediatamente después!


In [3]:
print("Zeros (Vector 1D):")
print(np.zeros(3))

print("\nOnes (Matriz 2x2):")
print(np.ones((2, 2))) # Nota que pasamos una tupla (2, 2) para el 'shape'

print("\nEmpty (Cuidado con la 'basura' de memoria):")
print(np.empty(4))


Zeros (Vector 1D):
[0. 0. 0.]

Ones (Matriz 2x2):
[[1. 1.]
 [1. 1.]]

Empty (Cuidado con la 'basura' de memoria):
[1. 1. 1. 1.]


---
##### 🛠️ Práctica 1.2: Inicialización rápida


Utiliza funciones integradas para:
1. Crear una matriz de 4 filas y 3 columnas llena de ceros.
2. Crear un vector de 5 elementos lleno de unos.


In [4]:
# Escribe tu código aquí




<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
# 1. Matriz 4x3 de ceros
matriz_ceros = np.zeros((4, 3))
print("Ceros:\n", matriz_ceros)

# 2. Vector 5 elementos unos
vector_unos = np.ones(5)
print("\nUnos:\n", vector_unos)
```
</details>


---
#### 1.3 Funciones de Rango y Secuencia (Arange, Linspace)

Cuando trabajas con gráficas, series de tiempo o ejes continuos, necesitarás generar rangos matemáticos exactos.

1. **`np.arange(inicio, fin, paso)`**:
   * Funciona casi idéntico al `range()` nativo de Python, pero retorna un array de NumPy y admite saltos (pasos) con decimales.
   * El límite `fin` siempre es **excluyente** (no se incluye).
   * **Uso ideal:** Cuando sabes exactamente de a cuánto quieres que salten los números (ej. saltar de a `0.5`).

2. **`np.linspace(inicio, fin, cantidad_elementos)`**:
   * En lugar de especificar de a cuánto saltar, tú especificas cuántos números totales quieres tener al final. NumPy hace la matemática y calcula el paso exacto para que estén espaciados de manera perfectamente uniforme.
   * El límite `fin` aquí **SÍ** se incluye por defecto.
   * **Uso ideal:** Especialmente útil en Machine Learning y gráficas cartesianas (matplotlib) para crear los ejes de una función.


In [5]:
print("Uso de arange (Paso conocido):")
print("De 0 a 9 (excluye 10):", np.arange(0, 10))
print("De 2 a 9 (saltando de a 2):", np.arange(2, 9, 2))

print("\nUso de linspace (Cantidad conocida):")
print("5 valores entre 0 y 10 (incluye el 10):", np.linspace(0, 10, num=5))


Uso de arange (Paso conocido):
De 0 a 9 (excluye 10): [0 1 2 3 4 5 6 7 8 9]
De 2 a 9 (saltando de a 2): [2 4 6 8]

Uso de linspace (Cantidad conocida):
5 valores entre 0 y 10 (incluye el 10): [ 0.   2.5  5.   7.5 10. ]


---
##### 🛠️ Práctica 1.3: Secuencias Numéricas


1. Utiliza `arange` para generar todos los números pares del 10 al 20 (incluyendo el 20). *(Pista: el límite superior debe ser 21 para que lo incluya).*
2. Utiliza `linspace` para generar exactamente 100 números espaciados entre el 0 y el 1.


In [6]:
# Escribe tu código aquí




<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
pares = np.arange(10, 21, 2)
print("Pares:", pares)

puntos = np.linspace(0, 1, 100)
print("100 Puntos:", puntos)
```
</details>


---
#### 1.4 Matriz Identidad (Eye)

En el álgebra lineal computacional, la matriz identidad es una matriz cuadrada especial que tiene unos (`1`) en su diagonal principal y ceros (`0`) en el resto de posiciones.

* **¿Para qué sirve?** La matriz identidad es el equivalente matricial del número `1`. Cualquier matriz multiplicada por su matriz identidad resulta en sí misma. Es vital para resolver sistemas de ecuaciones lineales, calcular matrices inversas, realizar descomposiciones (como PCA) y entrenar modelos como la regresión lineal.
* Usamos la función **`np.eye(n)`** para crearla, donde `n` es el número de filas y columnas.


In [7]:
print("Matriz Identidad de 3x3:")
print(np.eye(3))


Matriz Identidad de 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


---
##### 🛠️ Práctica 1.4: Identidad


Crea una matriz identidad de tamaño 5x5.


In [8]:
# Escribe tu código aquí




<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
identidad_5 = np.eye(5)
print(identidad_5)
```
</details>


---
### 2. Tipos de Datos (dtype) 🛠️

A diferencia de Python, que maneja los números genéricamente detrás de escena, NumPy es de bajo nivel (se acerca al lenguaje C). Por ende, requiere saber exactamente cuánta memoria física en RAM debe reservar para cada número.

Por defecto, si escribes `np.ones(5)`, NumPy asume que son puntos flotantes muy precisos (`float64`), lo que consume mucha memoria. Si sabes que solo manejarás números enteros, puedes forzar el tipo usando el atributo **`dtype`**.

**Tipos comunes:**
* `np.float64`: Decimales por defecto (alta precisión, alto consumo de memoria).
* `np.int64` o `np.int32`: Números enteros genéricos.
* `np.int8`: Enteros muy pequeños (del -128 al 127). ¡Excelente para ahorrar memoria al procesar imágenes (donde los píxeles van del 0 al 255)!


In [9]:
# Forzamos explícitamente a que sean enteros
array_enteros = np.ones(3, dtype=np.int32)
print("Array Entero:", array_enteros)
print("Tipo del array:", array_enteros.dtype)


Array Entero: [1 1 1]
Tipo del array: int32


---
##### 🛠️ Práctica 2: Casteo de tipos


Crea una matriz de ceros de 2x2. Obliga a que su tipo de dato sea **entero**. Imprime la matriz y su tipo de dato para verificar.


In [10]:
# Escribe tu código aquí




<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
ceros_enteros = np.zeros((2, 2), dtype=np.int32)
print(ceros_enteros)
print("Tipo:", ceros_enteros.dtype)
```
</details>


---
### 3. Atributos de un array

Un array suele ser un contenedor de tamaño fijo de elementos del mismo tipo y tamaño. **El número de dimensiones y elementos** en un array está definido por su **forma** (`shape`). La forma de un array es **una tupla de enteros no negativos que especifican el tamaño de cada dimensión.**

**En NumPy, las dimensiones se denominan ejes.** Esto significa que si tienes un array bidimensional (2D) con este aspecto:

```python
[[0., 0., 0.],
 [1., 1., 1.]]
```

Tu array tiene 2 ejes. El primer eje tiene una longitud de 2 y el segundo eje tiene una longitud de 3.

<img src="images/numpy_axes.png" width="600"/>

Los atributos más importantes de un objeto `ndarray` son:

* **ndarray.ndim:** el **número de ejes (dimensiones)** del array.
* **ndarray.shape:** las dimensiones del array. Esta es una tupla de enteros que indica el **tamaño del array en cada dimensión**. Para una matriz con n filas y m columnas, la forma será (n,m). Por lo tanto, la longitud de la tupla shape es el número de ejes, ndim.
* **ndarray.size:** el **número total de elementos del array**. Esto es igual al producto de los elementos de shape.
* **ndarray.dtype:** un objeto que describe el **tipo de los elementos en el array**. Se pueden crear o especificar `dtype`s utilizando los tipos estándar de Python. Además, NumPy proporciona tipos propios. numpy.int32, numpy.int16 y numpy.float64 son algunos ejemplos.
* **ndarray.itemsize:** el **tamaño en bytes de cada elemento del array**. Por ejemplo, un array de elementos de tipo float64 tiene un itemsize de 8 (=64/8), mientras que uno de tipo complex32 tiene un itemsize de 4 (=32/8). Es equivalente a ndarray.dtype.itemsize.
* **ndarray.data:** el **búfer que contiene los elementos reales del array**. Normalmente, no necesitaremos usar este atributo porque accederemos a los elementos de un array utilizando las funciones de indexación.

Debemos proporcionar listas que sean coherentes con las dimensiones y tipos de los ejes. Si no proporcionamos formas (o tipos) coherentes, NumPy optará por crear arrays de tipo `object`.

In [13]:
# NumPy convertirá las listas solo si son coherentes con las dimensiones de los ejes
# Para tener un array definido correctamente DEBEMOS tener elementos que tengan el mismo
# número de subelementos en cada eje
arr_obj = np.array([[0,1,2], [3,4,5], [6,7,8]])
arr_obj

# ¡NumPy convierte automáticamente a un tipo de dato común, si es posible!
arr_obj = np.array([[0,1,2], [3,4,"5"], [6,7,8]])
arr_obj

# De lo contrario, recurre al tipo 'object'
arr_obj = np.array([[0,1,2], [3,4,print], [6,7,8]])
arr_obj

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U21')

array([[0, 1, 2],
       [3, 4, <built-in function print>],
       [6, 7, 8]], dtype=object)

---
##### 🛠️ Práctica 3: Inspeccionando arrays


A continuación crearemos un Tensor 3D simulado con unos (`np.ones`). Un tensor 3D tiene tres valores en su shape: (profundidad/hojas, filas, columnas).

Instrucciones: Crea un array de unos con la forma `(2, 3, 4)`. Imprime directamente su `shape` y su `size` total para comprobar la construcción matemática (el tamaño debería dar 24).


In [ ]:
# Escribe tu código aquí




<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
tensor_3d = np.ones((2, 3, 4))
print("Shape del tensor:", tensor_3d.shape)
print("Size total (elementos):", tensor_3d.size)
```
</details>
