<table style="width: 100%; border-collapse: collapse; border: none; background: #f8fafc; border-left: 6px solid #1e3a8a; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
  <tr style="border: none;">
    <td style="vertical-align: middle; border: none; padding: 15px 20px;">
      <h1 style="margin: 0; color: #0f172a; font-size: 2.1em; font-family: system-ui, -apple-system, sans-serif; font-weight: 700; line-height: 1.2;">
        Operaciones con Arrays en Numpy
      </h1>
      <p style="margin: 6px 0 0 0; color: #64748b; font-size: 0.95em; font-family: system-ui, -apple-system, sans-serif;">
        Programación para Ciencia de Datos
      </p>
    </td>
    <td style="vertical-align: middle; text-align: right; border: none; padding: 15px 20px; min-width: 240px; font-family: system-ui, -apple-system, sans-serif;">
      <div style="font-size: 0.9em; color: #334155; line-height: 1.5;">
        <strong style="color: #1e3a8a; font-size: 1em;">Especialización en Ciencia de Datos</strong><br>
        <span style="color: #475569; font-weight: 600;">USTA Tunja</span><br><br>
        <b>Santiago A. Zúñiga M.</b><br>
        ✉️ <a href="mailto:gestorvirtualcienciadatos@ustatunja.edu.co" style="color: #2563eb; text-decoration: none; font-weight: 500;">gestorvirtualcienciadatos@ustatunja.edu.co</a>
      </div>
    </td>
  </tr>
</table>

---
## Operaciones con Arrays 

Una vez que has creado tus arrays, el siguiente paso lógico es comenzar a trabajar y operar matemáticamente con ellos. NumPy está diseñado específicamente para que este proceso sea increíblemente veloz e intuitivo.

En esta sección exploraremos la aritmética básica, el concepto mágico del "broadcasting", las reducciones estadísticas y el álgebra matricial.




---
### 1. Operaciones Básicas  ➕ ➖ ✖️ ➗

Es crucial entender que los operadores aritméticos básicos en NumPy se aplican **elemento por elemento** (element-wise). 

En el Python estándar, si usas el símbolo `+` en dos listas, Python las concatena (las une una detrás de otra). En NumPy, si usas `+` en dos matrices, NumPy **sumará matemáticamente las posiciones correspondientes** (por ejemplo, la posición `[0,0]` de la matriz A con la posición `[0,0]` de la matriz B).

¡Esta característica vectorizada es la que nos ahorra tener que escribir largos e ineficientes bucles `for`!

In [1]:
# Importar numpy y configurar salidas interactivas
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import numpy as np

# Creamos dos arrays del mismo tamaño
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

print("Suma (Elemento a elemento):")
print(data + ones)

print("\nResta:")
print(data - ones)

print("\nMultiplicación (NO matricial, sino posición por posición):")
print(data * data)

print("\nDivisión:")
print(data / data)


Suma (Elemento a elemento):
[2 3]

Resta:
[0 1]

Multiplicación (NO matricial, sino posición por posición):
[1 4]

División:
[1. 1.]


---
##### 🛠️ Práctica 1: Aritmética Básica



Imagina que tienes una matriz que representa el inventario de dos productos en tres tiendas (`inventario`), y te acaba de llegar un cargamento idéntico para cada tienda que quieres sumar al total (`llegada`).
Usa NumPy para sumar ambos arrays. Luego, asume que se dañó 1 producto de todos los lotes, así que réstale el escalar `1` a tu matriz resultante.

In [2]:
inventario = np.array([[10, 15, 20], [5, 10, 8]])
llegada = np.array([[5, 5, 5], [2, 2, 2]])

# Escribe tu código aquí

# nuevo_inventario = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
nuevo_inventario = inventario + llegada
inventario_final = nuevo_inventario - 1

print("Inventario Final:\n", inventario_final)
```
</details>


---
### 2. Broadcasting (Transmisión) 📡

El término **Broadcasting** (transmisión) describe la forma mágica y eficiente en la que NumPy maneja operaciones aritméticas entre arrays de *diferentes formas o tamaños*.

Normalmente, pensaríamos que para operar dos arrays deben tener dimensiones idénticas. Sin embargo, bajo ciertas restricciones lógicas, NumPy "transmite" o estira virtualmente el array más pequeño para que coincida con la forma del array más grande. 

**¿Por qué esto es genial?**
Lo hace a nivel de lenguaje C en segundo plano, sin tener que duplicar innecesariamente los datos en la memoria RAM. Evita copias de datos y bucles, llevando a implementaciones de algoritmos ultrarrápidos.

<img src="images/broadcasting.png" alt="NumPy Broadcasting" width="600"/>

El caso más común en el que usamos broadcasting es al operar una matriz contra un único número (un vector contra un escalar). Por ejemplo, si tienes una matriz de distancias en Millas y deseas convertirlo todo a Kilómetros (multiplicando por `1.6`), NumPy expandirá ese `1.6` para multiplicarlo por cada elemento.


In [3]:
# Un array (vector) y un escalar numérico
distancias_millas = np.array([1.0, 2.0, 5.0, 10.0])

# El número 1.6 hace 'broadcast' internamente a [1.6, 1.6, 1.6, 1.6] de forma ultrarrápida
distancias_km = distancias_millas * 1.6
print("Conversión a KM:", distancias_km)


Conversión a KM: [ 1.6  3.2  8.  16. ]


⚠️ **Nota sobre la compatibilidad:** Las dimensiones de tu array deben ser compatibles. Esto sucede cuando son iguales, o cuando una de las dimensiones es `1`. Si las dimensiones son totalmente asimétricas e incompatibles (ej. multiplicar una matriz 3x3 con un vector de 2 elementos), obtendrás un `ValueError`.


---
##### 🛠️ Práctica 2: Broadcasting



Tienes un array que representa los precios de 4 artículos en Dólares (`precios_usd`). Utilizando broadcasting, multiplica todo el array por la tasa de cambio actual (ej. `4000`) para obtener `precios_cop`.

In [4]:
precios_usd = np.array([19.99, 5.50, 100.0, 0.99])

# Escribe tu código aquí

# precios_cop = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
tasa_cambio = 4000
precios_cop = precios_usd * tasa_cambio

print("Precios en COP:", precios_cop)
```
</details>


---
### 3. Operaciones de Agregación (Reducción) 📉

Las funciones de agregación toman una estructura de datos masiva y la **colapsan o reducen** a un solo número (o a un vector pequeño) extrayendo información estadística vital de los datos en bruto.

NumPy está repleto de estas funciones. Además de `.min()`, `.max()`, y `.sum()`, puedes usar fácilmente `.mean()` (promedio), `.prod()` (multiplicación de todos los elementos), y `.std()` (desviación estándar).

Por defecto, si no le especificas nada, estas funciones **aplastarán** la matriz entera y te devolverán un estadístico global sobre todos los números contenidos en ella.


In [5]:
a = np.array([
    [0.45053314, 0.17296777, 0.34376245, 0.5510652],
    [0.54627315, 0.05093587, 0.40067661, 0.55645993],
    [0.12697628, 0.82485143, 0.26590556, 0.56917101]
])

print("Suma total de toda la matriz:", a.sum())
print("Valor mínimo en toda la matriz:", a.min())
print("Promedio global de toda la matriz:", a.mean())


Suma total de toda la matriz: 4.8595784
Valor mínimo en toda la matriz: 0.05093587
Promedio global de toda la matriz: 0.4049648666666667


**El parámetro Mágico: `axis`**

Rara vez querrás el promedio de toda tu hoja de cálculo. Generalmente querrás "el promedio de cada columna" (ej. temperatura media diaria) o "la suma de cada fila" (ej. notas totales por estudiante).

El parámetro `axis` (eje) controla cuál dimensión será "colapsada" matemáticamente:
*   `axis=0`: Recorre la matriz verticalmente hacia abajo. Colapsa las filas, entregando un resultado **por columna**.
*   `axis=1`: Recorre la matriz horizontalmente. Colapsa las columnas, entregando un resultado **por fila**.


In [6]:
# Retorna el valor mínimo contenido en CADA COLUMNA
# Al haber 4 columnas, obtenemos 4 resultados.
print("Mínimos por Columna (axis=0):", a.min(axis=0))

# Retorna la suma contenida en CADA FILA
# Al haber 3 filas, obtenemos 3 resultados.
print("Suma por Fila (axis=1):", a.sum(axis=1))


Mínimos por Columna (axis=0): [0.12697628 0.05093587 0.26590556 0.5510652 ]
Suma por Fila (axis=1): [1.51832856 1.55434556 1.78690428]


---
##### 🛠️ Práctica 3: Agregando por Ejes


Imagina que la siguiente matriz de 3x3 representa las notas de 3 estudiantes (las filas) en 3 asignaturas distintas (las columnas).

```python
notas = np.array([
    [3.5, 4.0, 4.2], # Estudiante 1
    [2.8, 3.1, 4.0], # Estudiante 2
    [4.5, 4.6, 4.8]  # Estudiante 3
])
```

Calcula e imprime:
1. La **nota máxima** obtenida en cada asignatura (`axis=0`).
2. El **promedio** de notas de cada estudiante (`axis=1`).


In [7]:
notas = np.array([
    [3.5, 4.0, 4.2],
    [2.8, 3.1, 4.0],
    [4.5, 4.6, 4.8] 
])

# Escribe tu código aquí

# maximas_asignaturas = ...
# promedios_estudiantes = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
maximas_asignaturas = notas.max(axis=0)
promedios_estudiantes = notas.mean(axis=1)

print("Nota máxima por materia:", maximas_asignaturas)
print("Promedio por estudiante:", promedios_estudiantes)
```
</details>


---
### 4. Operaciones Matriciales (Álgebra Lineal) 📐

Uno de los errores más comunes de los analistas que provienen de Matlab o R es creer que el operador asterisco `*` realizará el clásico "producto punto" del álgebra lineal. **No lo hace.** En NumPy, el `*` siempre hará un producto *elemento a elemento*.

Para realizar el auténtico **producto de matrices** (donde multiplicas filas por columnas matemáticamente), debes utilizar el operador **`@`** (introducido en Python 3.5) o invocar el método matricial **`.dot()`**.

Además, con mucha frecuencia necesitarás rotar o pivotar tu matriz, intercambiando las filas por las columnas. Esto se conoce como la matriz **transpuesta** y en NumPy puedes obtenerla instantáneamente llamando al atributo **`.T`**.


In [8]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print("Producto elemento a elemento (A * B):")
print(A * B)

print("\nProducto de Matrices de Álgebra Lineal (A @ B):")
print(A @ B)

print("\nTransposición (A.T):")
print("Matriz A original:\n", A)
print("Matriz A transpuesta:\n", A.T)


Producto elemento a elemento (A * B):
[[2 0]
 [0 4]]

Producto de Matrices de Álgebra Lineal (A @ B):
[[5 4]
 [3 4]]

Transposición (A.T):
Matriz A original:
 [[1 1]
 [0 1]]
Matriz A transpuesta:
 [[1 0]
 [1 1]]


---
##### 🛠️ Práctica 4: Álgebra Matricial



Dadas las matrices `X` e `Y`, transpone la matriz `X` y luego realiza el producto matricial entre tu nueva matriz transpuesta de X y la matriz Y. (Asegúrate de usar `@` o `.dot()`).

In [9]:
X = np.array([[1, 2], [3, 4], [5, 6]]) # Matriz 3x2
Y = np.array([[1, 0, 1], [0, 1, 0]]) # Matriz 2x3

# Escribe tu código aquí

# X_transpuesta = ...
# producto = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
X_transpuesta = X.T

# X_transpuesta ahora es 2x3. Multiplicada por Y que es 2x3... ¡Espera! 
# Las matemáticas dictan que no podemos multiplicar 2x3 con 2x3.
# Multipliquemos la original (3x2) por Y (2x3):
producto = X @ Y 
print("Producto Matricial (3x3):\n", producto)

# Si queríamos multiplicar la transpuesta de X (2x3), 
# necesitaríamos que Y también estuviera transpuesta (3x2)
print("\nProducto de ambas transpuestas (2x2):\n", X.T @ Y.T)
```
</details>
