<table style="width: 100%; border-collapse: collapse; border: none; background: #f8fafc; border-left: 6px solid #1e3a8a; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
  <tr style="border: none;">
    <td style="vertical-align: middle; border: none; padding: 15px 20px;">
      <h1 style="margin: 0; color: #0f172a; font-size: 2.1em; font-family: system-ui, -apple-system, sans-serif; font-weight: 700; line-height: 1.2;">
        Concatenación y Apilamiento de Arrays 
      </h1>
      <p style="margin: 6px 0 0 0; color: #64748b; font-size: 0.95em; font-family: system-ui, -apple-system, sans-serif;">
        Programación para Ciencia de Datos
      </p>
    </td>
    <td style="vertical-align: middle; text-align: right; border: none; padding: 15px 20px; min-width: 240px; font-family: system-ui, -apple-system, sans-serif;">
      <div style="font-size: 0.9em; color: #334155; line-height: 1.5;">
        <strong style="color: #1e3a8a; font-size: 1em;">Especialización en Ciencia de Datos</strong><br>
        <span style="color: #475569; font-weight: 600;">USTA Tunja</span><br><br>
        <b>Santiago A. Zúñiga M.</b><br>
        ✉️ <a href="mailto:gestorvirtualcienciadatos@ustatunja.edu.co" style="color: #2563eb; text-decoration: none; font-weight: 500;">gestorvirtualcienciadatos@ustatunja.edu.co</a>
      </div>
    </td>
  </tr>
</table>

---
## Concatenación y Apilamiento de Arrays 

En el mundo real, los datos rara vez vienen limpios y en un solo archivo. Usualmente tendrás que combinar datos de diferentes fuentes: las ventas de enero por un lado, las de febrero por otro.

NumPy ofrece dos operaciones fundamentales para unir (merge) múltiples arrays en un único array final: **Concatenación** (unión en un eje existente) y **Apilamiento o Stacking** (creación de un eje completamente nuevo).

<img src="images/stacking_concat.png" width="800"/>




---
### 1. Concatenación (Unión en un Eje Existente) 🔗

La función `np.concatenate()` toma una secuencia de arrays y los une a lo largo de un eje o dimensión **que ya existe**. Piensa en ello como tomar dos trenes y pegarlos vagón con vagón para hacer un tren más largo. El resultado sigue siendo un tren (misma cantidad de dimensiones).

**Regla Matemática Estricta:**
Para poder concatenar dos arrays, **absolutamente todos sus ejes deben tener la misma longitud**, con la única excepción del eje sobre el cual estás haciendo la concatenación. 

Por ejemplo, si tienes una matriz `[A, B, C, N1]` y otra `[A, B, C, N2]`, puedes concatenarlas en el último eje para obtener `[A, B, C, N1+N2]`. ¡Si `A`, `B` o `C` difieren, NumPy explotará!

In [1]:
# Configuración interactiva
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import numpy as np

# --- EJEMPLO 1D ---
arr1 = np.arange(1, 4) # [1, 2, 3] (Forma: 3,)
arr2 = np.arange(4, 7) # [4, 5, 6] (Forma: 3,)

print("Formas 1D:", arr1.shape, arr2.shape)

# Concatenamos vectores 1D [3] + [3] -> [6]
unidos_1d = np.concatenate([arr1, arr2], axis=0)
print("Vectores concatenados:", unidos_1d)


Formas 1D: (3,) (3,)
Vectores concatenados: [1 2 3 4 5 6]


In [2]:
# --- EJEMPLO 2D ---
arr3 = np.arange(1, 7).reshape(2, 3)
arr4 = np.arange(7, 13).reshape(2, 3)

print("Matriz 1:\n", arr3)
print("Matriz 2:\n", arr4)
print("\nFormas 2D:", arr3.shape, arr4.shape)

# Concatenación en el Eje 0 (Hacia abajo / Filas)
# [2, 3] + [2, 3] -> [4, 3]
concat_axis_0 = np.concatenate([arr3, arr4], axis=0)
print("\nConcatenación axis=0 (Pegado Vertical):\n", concat_axis_0)
print("Nueva forma:", concat_axis_0.shape)

# Concatenación en el Eje 1 (Hacia la derecha / Columnas)
# [2, 3] + [2, 3] -> [2, 6]
concat_axis_1 = np.concatenate([arr3, arr4], axis=1)
print("\nConcatenación axis=1 (Pegado Horizontal):\n", concat_axis_1)
print("Nueva forma:", concat_axis_1.shape)


Matriz 1:
 [[1 2 3]
 [4 5 6]]
Matriz 2:
 [[ 7  8  9]
 [10 11 12]]

Formas 2D: (2, 3) (2, 3)

Concatenación axis=0 (Pegado Vertical):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Nueva forma: (4, 3)

Concatenación axis=1 (Pegado Horizontal):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Nueva forma: (2, 6)


---
#### 🛠️ Práctica 1: Concatenando Bases de Datos


Imagina que tienes una base de datos tabular con la edad y el salario de 2 personas (matriz 2x2). Luego consigues los mismos datos para otras 3 personas (matriz 3x2). 
Usa `concatenate` para unirlas en una sola base de datos de 5 personas (matriz 5x2).


In [3]:
grupo_a = np.array([[25, 1500], [30, 2200]]) # 2 personas, 2 variables
grupo_b = np.array([[22, 1200], [45, 3500], [38, 2800]]) # 3 personas, 2 variables

# Escribe tu código aquí

# base_completa = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
# Como queremos apilar más "filas" (personas), usamos axis=0
base_completa = np.concatenate([grupo_a, grupo_b], axis=0)
print(base_completa)
print("Forma final:", base_completa.shape)
```
</details>


---
### 2. Apilamiento / Stacking (Unión en un NUEVO Eje) 🥞

A diferencia de la concatenación, el Apilamiento (`np.stack()`) crea una **dimensión completamente nueva**. 
Piensa en ello como tomar varias hojas de papel 2D (matrices) y "apilarlas" físicamente una encima de la otra para crear un libro 3D (un tensor).

**Regla Matemática Estricta:**
Para que NumPy pueda crear esta nueva dimensión perfecta, los arrays originales deben ser **100% idénticos en su forma** (mismas dimensiones, mismos elementos en cada dimensión).

Si apilas dos matrices de forma `[A, B, C, D]` en el último eje, obtendrás una estructura superior de forma `[A, B, C, D, 2]`.


In [4]:
# --- EJEMPLO 1D a 2D ---
# Apilar dos vectores 1D crea una matriz 2D
# arr1 y arr2 son [1,2,3] y [4,5,6] (Forma: 3,)

# Stacking en el eje 0 (Crea la dimensión al principio)
# [3] y [3] -> [2, 3]
stack_axis_0 = np.stack([arr1, arr2], axis=0)
print("Stack axis=0 (Crea filas):\n", stack_axis_0)
print("Forma:", stack_axis_0.shape)

# Stacking en el eje -1 (Último eje, crea la dimensión al final)
# [3] y [3] -> [3, 2]
stack_axis_1 = np.stack([arr1, arr2], axis=-1)
print("\nStack axis=-1 (Crea columnas pareadas):\n", stack_axis_1)
print("Forma:", stack_axis_1.shape)


Stack axis=0 (Crea filas):
 [[1 2 3]
 [4 5 6]]
Forma: (2, 3)

Stack axis=-1 (Crea columnas pareadas):
 [[1 4]
 [2 5]
 [3 6]]
Forma: (3, 2)


In [5]:
# --- EJEMPLO 2D a 3D ---
# arr3 y arr4 son matrices 2x3. Al apilarlas, pasaremos al mundo 3D.

# [2, 3] y [2, 3] -> [2, 2, 3] 
# (Se crea una dimensión '2' al inicio, representando "2 matrices, cada una de 2x3")
stack_2d_ax0 = np.stack([arr3, arr4], axis=0)
print("Stack 3D (axis=0):\n", stack_2d_ax0)
print("Forma:", stack_2d_ax0.shape)

# [2, 3] y [2, 3] -> [2, 3, 2]
# (Se emparejan los elementos individuales uno detrás de otro)
stack_2d_ax_last = np.stack([arr3, arr4], axis=-1)
print("\nStack 3D (axis=-1):\n", stack_2d_ax_last)
print("Forma:", stack_2d_ax_last.shape)


Stack 3D (axis=0):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Forma: (2, 2, 3)

Stack 3D (axis=-1):
 [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
Forma: (2, 3, 2)


---
#### 🛠️ Práctica 2: Apilando Capas de Color (Imágenes RGB)


En procesamiento de imágenes digitales, el color se representa separando los canales Rojo (R), Verde (G) y Azul (B). Tienes tres matrices 2D (5x5) que representan la intensidad de cada color de una minúscula imagen.
Utiliza `np.stack()` para apilarlas en el último eje (`axis=-1`) y crear un solo tensor 3D de forma `(5, 5, 3)` (Alto, Ancho, Canales).


In [6]:
R = np.ones((5, 5)) * 255   # Canal Rojo
G = np.zeros((5, 5))        # Canal Verde
B = np.zeros((5, 5))        # Canal Azul

# Escribe tu código aquí

# imagen_rgb = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
# Apilamos en el último eje para que los 3 canales queden en la "profundidad" de la imagen
imagen_rgb = np.stack([R, G, B], axis=-1)

print("Forma del Tensor de Imagen:", imagen_rgb.shape)
# Si te fijas en el primer pixel [0,0], verás que tiene [255, 0, 0] (Rojo puro)
print("Pixel [0,0]:", imagen_rgb[0, 0]) 
```
</details>
