<table style="width: 100%; border-collapse: collapse; border: none; background: #f8fafc; border-left: 6px solid #1e3a8a; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
  <tr style="border: none;">
    <td style="vertical-align: middle; border: none; padding: 15px 20px;">
      <h1 style="margin: 0; color: #0f172a; font-size: 2.1em; font-family: system-ui, -apple-system, sans-serif; font-weight: 700; line-height: 1.2;">
        Temas Avanzados: Aleatoriedad, Únicos y Expansión 
      </h1>
      <p style="margin: 6px 0 0 0; color: #64748b; font-size: 0.95em; font-family: system-ui, -apple-system, sans-serif;">
        Programación para Ciencia de Datos
      </p>
    </td>
    <td style="vertical-align: middle; text-align: right; border: none; padding: 15px 20px; min-width: 240px; font-family: system-ui, -apple-system, sans-serif;">
      <div style="font-size: 0.9em; color: #334155; line-height: 1.5;">
        <strong style="color: #1e3a8a; font-size: 1em;">Especialización en Ciencia de Datos</strong><br>
        <span style="color: #475569; font-weight: 600;">USTA Tunja</span><br><br>
        <b>Santiago A. Zúñiga M.</b><br>
        ✉️ <a href="mailto:gestorvirtualcienciadatos@ustatunja.edu.co" style="color: #2563eb; text-decoration: none; font-weight: 500;">gestorvirtualcienciadatos@ustatunja.edu.co</a>
      </div>
    </td>
  </tr>
</table>

---
## Temas Avanzados: Aleatoriedad, Únicos y Expansión 

En este cuaderno abordaremos tres herramientas vitales para cualquier científico de datos que trabaje con algoritmos numéricos o de Machine Learning: la generación de números pseudo-aleatorios, la extracción de valores únicos (frecuencias) y la manipulación avanzada de dimensiones "falsas".



---
### 1. Números Aleatorios (Random Numbers) 🎲

La generación de números aleatorios es la base de casi todo en Machine Learning: desde inicializar los pesos de una Red Neuronal Artificial, hasta mezclar (shuffle) un dataset para evitar sesgos, o separar los datos de entrenamiento y validación.

A nivel informático, la aleatoriedad perfecta no existe. Hablamos de números **pseudo-aleatorios**, generados por un algoritmo matemático complejo. Lo brillante de esto es que si le pasamos una "semilla" (`seed`) al algoritmo, la secuencia "aleatoria" será **exactamente la misma** cada vez que ejecutes el código, permitiendo que tus experimentos científicos sean 100% reproducibles.

*Nota: La forma moderna y recomendada (best practice) de generar números aleatorios en NumPy es instanciando un generador con `np.random.default_rng()`.*


In [1]:
# Configuración interactiva
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import numpy as np

# Instanciamos el Generador con una semilla (seed = 16)
rng = np.random.default_rng(seed=16)

# 1. Números Enteros Aleatorios
# El límite inferior es inclusivo, el superior es EXCLUSIVO. (Va del 0 al 4).
matriz_enteros = rng.integers(low=0, high=5, size=(2, 4))
print("Enteros (0 a 4):\n", matriz_enteros)

# 2. Distribución Uniforme (Flotantes)
# Cualquier número entre 0.0 y 1.0 tiene exactamente la misma probabilidad de salir
un_solo_numero = rng.uniform(low=0.0, high=1.0)
print("\nUn solo número (Distribución Uniforme):", un_solo_numero)

# 3. Distribución Normal (Campana de Gauss)
# loc = media (mean), scale = Desviación Estándar (std)
matriz_normal = rng.normal(loc=0.0, scale=1.0, size=(2, 4))
print("\nDistribución Normal (Media 0, Std 1):\n", matriz_normal)


Enteros (0 a 4):
 [[2 2 4 2]
 [3 0 2 1]]

Un solo número (Distribución Uniforme): 0.6215090383806794

Distribución Normal (Media 0, Std 1):
 [[-0.38518938  0.54417719 -0.36622168 -1.42484851]
 [-0.70385912  0.13616234 -0.91517473 -0.19147102]]


---
#### 🛠️ Práctica 1: Aleatoriedad


Crea un generador aleatorio utilizando la semilla `42` (la más famosa en programación). 
1. Genera un vector de 5 números enteros aleatorios entre el `10` y el `20` (inclusivos).
2. Ejecuta la celda varias veces. ¿Cambian los números? ¿Por qué?


In [2]:
# Escribe tu código aquí

# rng_practica = ...
# vector_aleatorio = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
rng_practica = np.random.default_rng(seed=42)
# Para que el 20 sea inclusivo, el 'high' debe ser 21. Opcionalmente puedes usar endpoint=True
vector_aleatorio = rng_practica.integers(low=10, high=21, size=5)
print(vector_aleatorio)
# Respuesta a la pregunta: Los números NO cambian al re-ejecutar porque la "semilla" 
# (42) ancla el algoritmo a una secuencia fija. Si cambias el 42 por 43, la secuencia será otra.
```
</details>


---
### 2. Elementos Únicos y Conteos 🔍

En análisis exploratorio de datos (EDA), una de las primeras cosas que querrás saber sobre una columna categórica (e.g., el estrato social, el género, la ciudad) es: **¿Cuáles son las categorías únicas y cuántas personas hay en cada una?**

La función `np.unique()` es la navaja suiza para esto. Es mucho más poderosa que la función `set()` nativa de Python porque, además de darte los elementos únicos y ordenados, te permite extraer **los índices originales** y **la frecuencia** (conteo) de cada elemento.


In [3]:
# Imaginemos que este array representa las edades de un grupo de personas
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

# Obtener solo los valores únicos
valores_unicos = np.unique(a)
print("Valores únicos ordenados:", valores_unicos)

# Obtener los únicos y sus índices en el array original (la primera vez que aparece cada número)
unicos, indices = np.unique(a, return_index=True)
print("\nÍndice donde aparece el número '12' por primera vez:", indices[1]) # '12' es el segundo valor único

# Obtener la FRECUENCIA (conteos) de cada elemento
unicos, conteos = np.unique(a, return_counts=True)
print("\nFrecuencia (veces que aparece cada edad):")
for u, c in zip(unicos, conteos):
    print(f"La edad {u} aparece {c} veces.")


Valores únicos ordenados: [11 12 13 14 15 16 17 18 19 20]

Índice donde aparece el número '12' por primera vez: 2

Frecuencia (veces que aparece cada edad):
La edad 11 aparece 3 veces.
La edad 12 aparece 2 veces.
La edad 13 aparece 2 veces.
La edad 14 aparece 2 veces.
La edad 15 aparece 1 veces.
La edad 16 aparece 1 veces.
La edad 17 aparece 1 veces.
La edad 18 aparece 1 veces.
La edad 19 aparece 1 veces.
La edad 20 aparece 1 veces.


---
#### 🛠️ Práctica 2: Frecuencias


Tienes un vector que representa el resultado de tirar un dado de 6 caras, 20 veces.
Usando `np.unique()`, descubre **cuántas veces cayó el número 6**.


In [4]:
# Lanzamiento de dados (Semilla fijada para reproducibilidad)
dados = np.random.default_rng(seed=777).integers(1, 7, size=20)
print("Lanzamientos:", dados)

# Escribe tu código aquí

# ...



Lanzamientos: [6 4 3 3 1 4 3 6 2 2 2 3 3 4 3 4 3 5 1 3]


<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
caras_unicas, frecuencias = np.unique(dados, return_counts=True)
print("Caras resultantes:", caras_unicas)
print("Frecuencia de caras:", frecuencias)

# Opcional (Programático):
# Buscamos en qué posición está el 6 en 'caras_unicas'
indice_seis = np.where(caras_unicas == 6)[0][0]
print(f"El número 6 cayó {frecuencias[indice_seis]} veces.")
```
</details>


---
### 3. Expandiendo y Comprimiendo Dimensiones (Expand & Squeeze) 🗜️

En bibliotecas de Deep Learning como TensorFlow o PyTorch, a menudo te encontrarás con errores de dimensión. Por ejemplo, una red neuronal convolucional (CNN) *exige* que las imágenes tengan 3 dimensiones: `[Alto, Ancho, Canales de Color]`. 

¿Qué pasa si tienes una imagen en blanco y negro (escala de grises) de `[28, 28]`? ¡La red neuronal fallará porque espera 3 dimensiones! Para solucionar esto, necesitas añadir una dimensión "falsa" o "vacía" de tamaño 1, convirtiéndola en `[28, 28, 1]`. Los datos siguen siendo exactamente los mismos, pero la **arquitectura dimensional** ha cambiado.

<img src="images/expand_squeeze.png" width="700"/>


In [5]:
# Recordatorio: Un vector 1D no es ni "fila" ni "columna" matemáticamente. Es solo un vector.
arr = np.arange(5)
print("Forma original:", arr.shape)

# Podemos convertirlo artificialmente en un "Vector Fila" (1x5) o "Vector Columna" (5x1) usando reshape
print("Vector Fila:", arr.reshape(1, -1).shape)
print("Vector Columna:", arr.reshape(-1, 1).shape)


Forma original: (5,)
Vector Fila: (1, 5)
Vector Columna: (5, 1)


In [6]:
# --- EXPANDIENDO (Añadiendo Dimensiones Falsas) ---
matriz_2d = np.arange(9).reshape(3, 3)
print("\nMatriz original:\n", matriz_2d)
print("Forma 2D:", matriz_2d.shape)

# Método 1: Usando reshape y agregando un '1'
expandida_res = np.reshape(matriz_2d, [3, 3, 1])
print("Expandida con reshape:", expandida_res.shape)

# Método 2: Usando np.expand_dims (El método explícito preferido)
# axis=-1 significa "agrega la dimensión vacía al final"
expandida = np.expand_dims(matriz_2d, axis=-1)
print("Expandida con expand_dims:", expandida.shape)


# --- COMPRIMIENDO (Eliminando Dimensiones Falsas) ---
# La función np.squeeze() destruye todas las dimensiones cuyo tamaño sea exactamente '1'
comprimida = np.squeeze(expandida, axis=-1)
print("\nComprimida con squeeze (Volvió a la normalidad):", comprimida.shape)



Matriz original:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Forma 2D: (3, 3)
Expandida con reshape: (3, 3, 1)
Expandida con expand_dims: (3, 3, 1)

Comprimida con squeeze (Volvió a la normalidad): (3, 3)


---
#### 🛠️ Práctica 3: Expand y Squeeze


Tienes un tensor 4D que representa un lote de procesamiento de una red neuronal: `[Tamaño_Lote, Alto, Ancho, Canales]`. 
Actualmente su forma es `(1, 128, 128, 1)` (Una sola imagen, 128x128, en blanco y negro).
Usa `np.squeeze()` sin especificar el `axis` para ver qué sucede cuando omites el eje explícito.


In [7]:
tensor_red = np.zeros((1, 128, 128, 1))

# Escribe tu código aquí

# tensor_aplastado = ...



<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
# Si no especificamos el 'axis', np.squeeze destruirá TODOS los ejes que midan 1.
# Por lo tanto, destruirá el eje 0 (Tamaño de lote) y el eje 3 (Canales).
tensor_aplastado = np.squeeze(tensor_red)

print("Forma final:", tensor_aplastado.shape) # Debería ser simplemente (128, 128)
```
</details>
